# Generated by Django 5.2.6 on 2025-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumiveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumivel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='consumiveis/'),
        ),
    ]
